/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author LENOVO Z40-75
 */
public class Dokter extends javax.swing.JFrame {

    /**
     * Creates new form Dokter
     */
    public Dokter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jtxtwaktu = new javax.swing.JTextField();
        jtxtnama = new javax.swing.JTextField();
        jtxtalamat = new javax.swing.JTextField();
        jtxtusia = new javax.swing.JTextField();
        jtxtjenis = new javax.swing.JTextField();
        jtxtgol = new javax.swing.JTextField();
        jtxtstatus = new javax.swing.JTextField();
        jtxtkewar = new javax.swing.JTextField();
        jtxtspesial = new javax.swing.JTextField();
        jconadokt = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 255));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Pemilihan Dokter");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(150, 20, 340, 90);

        jLabel2.setText("Pilih Dokter");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 140, 100, 20);

        jLabel3.setBackground(new java.awt.Color(255, 153, 255));
        jLabel3.setText("Identitas");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 190, 90, 20);

        jLabel4.setText("Nama");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 240, 41, 20);

        jLabel5.setText("Dokter Spesialis");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(70, 560, 130, 20);

        jLabel6.setText("Alamat");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(70, 280, 50, 20);

        jLabel7.setText("Usia");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(70, 320, 30, 20);

        jLabel8.setText("Jenis Kelamin");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(70, 360, 110, 20);

        jLabel9.setText("Golongan Darah");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(70, 400, 120, 20);

        jLabel10.setText("Status");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(70, 440, 43, 20);

        jLabel11.setText("Kewarganegaraan");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(70, 480, 130, 20);

        jLabel12.setText("Waktu Praktek");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(70, 520, 110, 20);

        jtxtwaktu.setEnabled(false);
        getContentPane().add(jtxtwaktu);
        jtxtwaktu.setBounds(250, 560, 170, 26);

        jtxtnama.setEnabled(false);
        getContentPane().add(jtxtnama);
        jtxtnama.setBounds(250, 240, 170, 26);

        jtxtalamat.setEnabled(false);
        jtxtalamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtalamatActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtalamat);
        jtxtalamat.setBounds(250, 280, 170, 26);

        jtxtusia.setEnabled(false);
        getContentPane().add(jtxtusia);
        jtxtusia.setBounds(250, 320, 170, 26);

        jtxtjenis.setEnabled(false);
        getContentPane().add(jtxtjenis);
        jtxtjenis.setBounds(250, 360, 170, 26);

        jtxtgol.setEnabled(false);
        getContentPane().add(jtxtgol);
        jtxtgol.setBounds(250, 400, 170, 26);

        jtxtstatus.setEnabled(false);
        getContentPane().add(jtxtstatus);
        jtxtstatus.setBounds(250, 440, 170, 26);

        jtxtkewar.setEnabled(false);
        getContentPane().add(jtxtkewar);
        jtxtkewar.setBounds(250, 480, 170, 26);

        jtxtspesial.setEnabled(false);
        getContentPane().add(jtxtspesial);
        jtxtspesial.setBounds(250, 520, 170, 26);

        jconadokt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih Salah Satu --", "dr. Ritza Kufita", "dr. Icha Kufita", "dr. Ninik H", "dr. Rezita C", "dr. Reyza A", "drg. Rizqia", "drg. Ritzata", " " }));
        jconadokt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jconadoktActionPerformed(evt);
            }
        });
        getContentPane().add(jconadokt);
        jconadokt.setBounds(200, 140, 200, 26);

        jPanel1.setBackground(new java.awt.Color(255, 204, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(60, 200, 380, 420);

        jPanel2.setBackground(new java.awt.Color(255, 153, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 510, 630);

        setBounds(0, 0, 520, 687);
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtalamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtalamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtalamatActionPerformed

    private void jconadoktActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jconadoktActionPerformed
if (jconadokt.getSelectedItem().equals("dr. Ritza Kufita"))
{
    jtxtnama.setText("dr. Ritza Kufita");
    jtxtalamat.setText("Jl. Kauman 31, Malang");
    jtxtusia.setText("23 Tahun");
    jtxtjenis.setText("Perempuan");
    jtxtgol.setText("A");
    jtxtstatus.setText("Menikah");
    jtxtkewar.setText("Indonesia");
    jtxtspesial.setText("Dokter Umum");
    jtxtwaktu.setText(" Pagi (07.00 - 15.00");
}
else if (jconadokt.getSelectedItem().equals("dr. Icha Kufita")){
    jtxtnama.setText("dr. Icha Kufita");
    jtxtalamat.setText("Jl. Srengat 13, Malang");
    jtxtusia.setText("20 Tahun");
    jtxtjenis.setText("Perempuan");
    jtxtgol.setText("AB");
    jtxtstatus.setText("Belum Menikah");
    jtxtkewar.setText("Indonesia");
    jtxtspesial.setText("Dokter Bedah");
    jtxtwaktu.setText(" Pagi (08.00 - 12.00");
    }
else if (jconadokt.getSelectedItem().equals("dr. Ninik H")){
    jtxtnama.setText("dr. Ninik H");
    jtxtalamat.setText("Jl. Mangga 22, Malang");
    jtxtusia.setText("33 Tahun");
    jtxtjenis.setText("Perempuan");
    jtxtgol.setText("O");
    jtxtstatus.setText("Menikah");
    jtxtkewar.setText("Indonesia");
    jtxtspesial.setText("Dokter Anastesi");
    jtxtwaktu.setText(" Pagi (09.00 - 12.00");
    }//GEN-LAST:event_jconadoktActionPerformed
else if (jconadokt.getSelectedItem().equals("dr. Rezita C")){
    jtxtnama.setText("dr. Rezita C");
    jtxtalamat.setText("Jl. Kenari 19, Malang");
    jtxtusia.setText("26 Tahun");
    jtxtjenis.setText("Perempuan");
    jtxtgol.setText("A");
    jtxtstatus.setText("Menikah");
    jtxtkewar.setText("Indonesia");
    jtxtspesial.setText("Dokter Anak");
    jtxtwaktu.setText(" Pagi (08.00 - 17.00");
    }
    else if (jconadokt.getSelectedItem().equals("dr. Reyza A")){
    jtxtnama.setText("dr. Reyza A");
    jtxtalamat.setText("Jl. Kembang 18, Malang");
    jtxtusia.setText("23 Tahun");
    jtxtjenis.setText("Perempuan");
    jtxtgol.setText("AB");
    jtxtstatus.setText("Belum Menikah");
    jtxtkewar.setText("Indonesia");
    jtxtspesial.setText("Dokter Kecantikan");
    jtxtwaktu.setText(" Pagi (08.00 - 17.00");
    }
else if (jconadokt.getSelectedItem().equals("drg. Rizqia")){
    jtxtnama.setText("drg. Rizqia");
    jtxtalamat.setText("Jl. Kandung 37, Malang");
    jtxtusia.setText("27 Tahun");
    jtxtjenis.setText("Perempuan");
    jtxtgol.setText("O");
    jtxtstatus.setText("Menikah");
    jtxtkewar.setText("Indonesia");
    jtxtspesial.setText("Dokter Gigi");
    jtxtwaktu.setText(" Pagi (08.00 - 14.00");
    }
else if (jconadokt.getSelectedItem().equals("drg. Ritzata")){
    jtxtnama.setText("drg. Ritzata");
    jtxtalamat.setText("Jl. Kawi 112, Malang");
    jtxtusia.setText("30 Tahun");
    jtxtjenis.setText("Perempuan");
    jtxtgol.setText("B");
    jtxtstatus.setText("Menikah");
    jtxtkewar.setText("Indonesia");
    jtxtspesial.setText("Dokter Gigi");
    jtxtwaktu.setText(" Malam (14.00 - 20.00");
    }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dokter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> jconadokt;
    private javax.swing.JTextField jtxtalamat;
    private javax.swing.JTextField jtxtgol;
    private javax.swing.JTextField jtxtjenis;
    private javax.swing.JTextField jtxtkewar;
    private javax.swing.JTextField jtxtnama;
    private javax.swing.JTextField jtxtspesial;
    private javax.swing.JTextField jtxtstatus;
    private javax.swing.JTextField jtxtusia;
    private javax.swing.JTextField jtxtwaktu;
    // End of variables declaration//GEN-END:variables
}
